// @ts-check

/**
 * Sidebar configuration for Docusaurus.
 * This file is auto-generated by scripts/generateSidebar.js
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    "intro",
    {
      type: "doc",
      id: "authentication",
      label: "Authentication"
    },
    {
      type: "doc",
      id: "validate-account",
      label: "Validate Account"
    },
    {
      type: "doc",
      id: "get-balance",
      label: "Get Balance"
    },
    {
      type: "doc",
      id: "validate-transaction-request",
      label: "Validate Transaction Request"
    },
    {
      type: "doc",
      id: "direct-payout",
      label: "Direct Payout"
    },
    {
      type: "doc",
      id: "direct-collection",
      label: "Direct Collection"
    },
    {
      type: "doc",
      id: "get-statement",
      label: "Get Statement"
    },
    {
      type: "doc",
      id: "get-products",
      label: "Get Products"
    },
    {
      type: "doc",
      id: "get-transaction",
      label: "Get Transaction"
    },
    /* {
      type: "doc",
      id: "get-pegpay-balance",
      label: "Get PegPay Balance"
    }, */
    {
      type: "doc",
      id: "webhooks",
      label: "Webhooks"
    },
    {
      type: "doc",
      id: "error-handling",
      label: "Error Handling"
    }
  ]
};

export default sidebars;